N:
  - 100
timeout: 5
epsilon: 10
delta: 1e-7
rdp:
  - 1
  - 0
n: 50
t: 30_000
elephants: "/users/yilegu/PrivateKube/evaluation/macrobenchmark/logs/amazon/classification/product-ff-event-1023-130413"
mice: "/users/yilegu/PrivateKube/evaluation/macrobenchmark/logs/amazon/statistics/avg_rating-event-gaussian-1023-130524"
mice_ratio: 0.75
m: 300
b: 10